### ISSUE TITLE
Tracking Issue for Web Server Enhancements

### ISSUE THREAD

**Issue by c9r** [swimos/swim#4]
swimOS contains an explicitly flow-controlled HTTP and WebSocket implementation. The HTTP and WebSocket wire protocols are implemented as a family of incremental `swim.codec` `Parser`s and `Writer`s in [`swim.http`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.http) and [`swim.ws`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.ws). These wire protocol implementations are then bound to flow-controller `swim.io` `Modem`s by [`swim.io.http`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.io.http) and [`swim.io.ws`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.io.ws).

swimOS runs an internal Web server built on these HTTP and WebSocket implementations, contained in [`swim.service.web`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-mesh-java/swim.service.web). The primary purpose of this web server has historically been to open WARP WebSockets. Over time, we added HTTP lanes, which get routed through the internal web server, as well as basic static resource serving. But HTTP lanes have been limited by fixed routing rules, and static resource servicing has been limited by serving up a single root document directory.

`swim.service.web` is itself built on top of [`swim.web`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.web), which is intended to implement generic web server capabilities, independent of any swimOS fabric integration. We'd like to enhance our web server with the following capabilities:

- [ ] HTTP Routing Directives
- [ ] Web Routing DSL
- [ ] HTTP Caching Directives
- [ ] HTTP CORS Directives
- [ ] HTTP Lane Directives
- [ ] WebSocket Lane Directives
